site_name: MoBagel Docs
site_description: MoBagel API Documentation
docs_dir: mkdocs
site_dir: docs
site_favicon: favicon.png
extra_css: [extra.css]
theme_dir: cinder
# theme: united

pages:
# - Home: index.md
# - Get Started: get-started.md
- Getting Started: index.md

# - Examples:
#     - Smart Home: examples/smart-home.md
#     - Vending Machine: examples/vending-machine.md
#     - Wearable Device: examples/wearable-device.md
- Integrations:
    - REST: integrations/rest.md
    - C: integrations/c.md
<<<<<<< HEAD
    - iOS: integrations/ios.md
    - python: integrations/python.md
    - node: integrations/node.md
=======
    - iOS Objective C: integrations/ios_objective_c.md
    - iOS Swift: integrations/ios_swift.md
>>>>>>> b228e72ccf4d8679d5eeff56caf9618e7cbe6904
    # - Java: integrations/java.md
    # - PHP: integrations/php.md
# - User Guide:
    # - Configuration: user-guide/configuration.md
- Glossary: glossary.md
    # - Authentication: user-guide/authentication.md
    # - Error Handling: user-guide/error-handling.md
- Use Cases: 
    - Smart Home: cases/smart-home.md
    - Vending Machine: cases/vending-machine.md
    - Wearable Device: cases/wearable-device.md
