site_name: MoBagel Docs
site_description: MoBagel API Documentation
docs_dir: mkdocs
site_dir: docs
site_favicon: favicon.png
extra_css: [extra.css]
theme_dir: cinder
google_analytics: ['UA-70490559-1', 'mobagel.com']
# theme: united

pages:

- Get Started: 
    - Connect To MoBagel: index.md
    - MoBagel Dashboard: started/dashboard.md

- Integrations:
    - REST: integrations/rest.md
#    - Python: integrations/python.md
#    - Node: integrations/node.md
#    - Java: integrations/java.md
#    - PHP: integrations/php.md
#    - C++: integrations/c++.md
#    - iOS Swift: integrations/ios_swift.md
#    - iOS Objective C: integrations/ios_objective_c.md

- Reference:
    - Glossary: glossary.md
    - Examples: examples.md

# - Use Cases: 
#     - Smart Home: cases/smart-home.md
#     - Vending Machine: cases/vending-machine.md
#     - Wearable Device: cases/wearable-device.md
