site_name: Bagel API Docs
site_description: Bagel API Documentation
docs_dir: mkdocs
site_dir: docs

# theme: readthedocs
# theme: united

pages:
- Home: index.md
- Get Started: get-started.md
- User Guide:
    - Configuration: user-guide/configuration.md
    - Introduction: user-guide/introduction.md
    # - Authentication: user-guide/authentication.md
    - Error Handling: user-guide/error-handling.md
- Examples:
    - Smart Home: examples/smart-home.md
    - Vending Machine: examples/vending-machine.md
    - Wearable Device: examples/wearable-device.md
- SDK:
    - C: sdk/c.md
    - Java: sdk/java.md
    - PHP: sdk/php.md
